version: '3.2'
services:

  mysql:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    container_name: mariadb-test
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test